const filmResponse = {
	contents: [
		{
			title: "",
			shows: [
				{
					about: " about about about",
					age_category: "1371",
					category_fk: "جنایی",
					cover: "https://cdn.soft98.ir/microsoft%20edge.jpg",
					director: "director",
					duration: "01:25",
					genres: ["genre"],
					id: "id1",
					image: "https://cdn.soft98.ir/CrystalDiskMark.png",
					name: "گشت 3",
					producer: "producer",
					release_date: "release_date",
					samfaa_id: "samfaa_id",
					slug: "slug",
					trailer: "trailer",
				},

				{
					about: " about about about",
					age_category: "1371",
					category_fk: "جنایی",
					cover: "https://cdn.soft98.ir/microsoft%20edge.jpg",
					director: "director",
					duration: "01:25",
					genres: ["genre"],
					id: "id2",
					image: "https://cdn.soft98.ir/CrystalDiskMark.png",
					name: "گشت 2",
					producer: "producer",
					release_date: "release_date",
					samfaa_id: "samfaa_id",
					slug: "slug",
					trailer: "trailer",
				},
				{
					about: " about about about",
					age_category: "1371",
					category_fk: "جنایی",
					cover: "https://cdn.soft98.ir/microsoft%20edge.jpg",
					director: "director",
					duration: "01:25",
					genres: ["genre"],
					id: "id2",
					image: "https://cdn.soft98.ir/CrystalDiskMark.png",
					name: "گشت 2",
					producer: "producer",
					release_date: "release_date",
					samfaa_id: "samfaa_id",
					slug: "slug",
					trailer: "trailer",
				},
			],
		},
	],
};

export { filmResponse };
